#!/bin/bash
#Initial Wifi Int Config
ifconfig $1 up 192.168.0.1 255.255.255.0
sleep 2
if [ "$(ps -e | grep dhcpd)" == "" ]; then
dhcpd $1 & 
fi
host apd /etc/hostapd/hostapd.conf 1> dev/null
killall dhcpd
